# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5acf46da38d890c5bd7583983b9434ebf9136d38b655ea9b08060844805ac77ce397d2cfba2fdded8576b047014fd9cc9556d2366d9cec16383416374bd94346

test:
  secret_key_base: 4977c4d8749856fae61ce73aa2bc15727351c9b69de231726584841d4b7cd98798e29295c18063081ef9ee931515e3d439af2327b39716578eab7fad3e1e0ca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
